# This workflow will install Python dependencies, ganache-cli and run tests for smart contracts

name: Smart contract test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Use Node.js 14.6
      uses: actions/setup-node@v3
      with:
        node-version: 14.6
        cache: 'npm'
    - name: Install poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        directory: smart_contracts
        file_name: .env
        fail_on_empty: false
    - name: Install ganache
      run: npm install -g ganache-cli
    - name: Install dependencies
      run: poetry install
    - name: Test smart contract
      working-directory: ./smart_contracts
      run: poetry run brownie test
